/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
import syntaxtree.*;

public class MiniJavaParser implements MiniJavaParserConstants {

  final public Program Goal() throws ParseException {MainClass m; ClassDeclList cl = new ClassDeclList(); ClassDecl c;
    m = MainClass();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CLASS:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      c = TypeDeclaration();
cl.addElement(c);
    }
    jj_consume_token(0);
{if ("" != null) return new Program(m.line, m.column, m, cl);}
    throw new Error("Missing return statement in function");
}

  final public MainClass MainClass() throws ParseException {Identifier i1, i2; Statement s; Token t = null;
    t = jj_consume_token(CLASS);
    i1 = Identifier();
    jj_consume_token(LBRACE);
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(VOID);
    jj_consume_token(MAIN);
    jj_consume_token(LPAREN);
    jj_consume_token(STRING);
    jj_consume_token(LBRACK);
    jj_consume_token(RBRACK);
    i2 = Identifier();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    s = Statement();
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
{if ("" != null) return new MainClass(t.beginLine, t.beginColumn, i1, i2, s);}
    throw new Error("Missing return statement in function");
}

  final public ClassDecl TypeDeclaration() throws ParseException {ClassDecl c;
    if (jj_2_1(3)) {
      c = ClassDeclaration();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CLASS:{
        c = ClassExtendsDeclaration();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return c;}
    throw new Error("Missing return statement in function");
}

  final public ClassDecl ClassDeclaration() throws ParseException {Identifier i; VarDeclList vl = new VarDeclList(); VarDecl v; MethodDeclList ml = new MethodDeclList(); MethodDecl m; Token t = null;
    jj_consume_token(CLASS);
    i = Identifier();
    jj_consume_token(LBRACE);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case BOOLEAN:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      v = VarDeclaration();
vl.addElement(v);
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      m = MethodDeclaration();
ml.addElement(m);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new ClassDeclSimple(t.beginLine, t.beginColumn, i, vl, ml);}
    throw new Error("Missing return statement in function");
}

  final public ClassDecl ClassExtendsDeclaration() throws ParseException {Identifier i, j; VarDeclList vl = new VarDeclList(); VarDecl v; MethodDeclList ml = new MethodDeclList(); MethodDecl m; Token t = null;
    jj_consume_token(CLASS);
    i = Identifier();
    jj_consume_token(EXTENDS);
    j = Identifier();
    jj_consume_token(LBRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case BOOLEAN:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      v = VarDeclaration();
vl.addElement(v);
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      m = MethodDeclaration();
ml.addElement(m);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new ClassDeclExtends(t.beginLine, t.beginColumn, i, j, vl, ml);}
    throw new Error("Missing return statement in function");
}

  final public VarDecl VarDeclaration() throws ParseException {Type t; Identifier i;
    t = Type();
    i = Identifier();
    jj_consume_token(SEMI);
{if ("" != null) return new VarDecl(t.line, t.column, t, i);}
    throw new Error("Missing return statement in function");
}

  final public MethodDecl MethodDeclaration() throws ParseException {Type t; Identifier i; FormalList fl = new FormalList(); VarDeclList vl = new VarDeclList(); VarDecl v; StatementList sl = new StatementList(); Statement s; Exp e; Token tok = null;
    tok = jj_consume_token(PUBLIC);
    t = Type();
    i = Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case BOOLEAN:
    case IDENTIFIER:{
      fl = FormalParameterList();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    label_6:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_6;
      }
      v = VarDeclaration();
vl.addElement(v);
    }
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case PRINTLN:
      case LBRACE:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_7;
      }
      s = Statement();
sl.addElement(s);
    }
    jj_consume_token(RETURN);
    e = Expression();
    jj_consume_token(SEMI);
    jj_consume_token(RBRACE);
{if ("" != null) return new MethodDecl(tok.beginLine, tok.beginColumn, t, i, fl, vl, sl, e);}
    throw new Error("Missing return statement in function");
}

  final public FormalList FormalParameterList() throws ParseException {FormalList fl = new FormalList(); Formal f;
    f = FormalParameter();
fl.addElement(f);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_8;
      }
      f = FormalParameterRest();
fl.addElement(f);
    }
{if ("" != null) return fl;}
    throw new Error("Missing return statement in function");
}

  final public Formal FormalParameter() throws ParseException {Type t; Identifier i;
    t = Type();
    i = Identifier();
{if ("" != null) return new Formal(t.line, t.column, t, i);}
    throw new Error("Missing return statement in function");
}

  final public Formal FormalParameterRest() throws ParseException {Formal f;
    jj_consume_token(COMMA);
    f = FormalParameter();
{if ("" != null) return f;}
    throw new Error("Missing return statement in function");
}

  final public Type Type() throws ParseException {Type t; Identifier i;
    if (jj_2_3(3)) {
      t = ArrayType();
{if ("" != null) return t;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BOOLEAN:{
        t = BooleanType();
{if ("" != null) return t;}
        break;
        }
      case INT:{
        t = IntegerType();
{if ("" != null) return t;}
        break;
        }
      case IDENTIFIER:{
        i = Identifier();
{if ("" != null) return new IdentifierType(i.line, i.column, i.s);}
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  final public Type ArrayType() throws ParseException {Token t = null;
    t = jj_consume_token(INT);
    jj_consume_token(LBRACK);
    jj_consume_token(RBRACK);
{if ("" != null) return new IntArrayType(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
}

  final public Type BooleanType() throws ParseException {Token t = null;
    t = jj_consume_token(BOOLEAN);
{if ("" != null) return new BooleanType(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
}

  final public Type IntegerType() throws ParseException {Token t = null;
    t = jj_consume_token(INT);
{if ("" != null) return new IntegerType(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
}

  final public Identifier Identifier() throws ParseException {Token t = null;
    t = jj_consume_token(IDENTIFIER);
{if ("" != null) return new Identifier(t.beginLine, t.beginColumn, t.image);}
    throw new Error("Missing return statement in function");
}

  final public Exp PrimaryExpression() throws ParseException {Exp e; Identifier i;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      e = IntegerLiteral();
      break;
      }
    case TRUE:{
      e = TrueLiteral();
      break;
      }
    case FALSE:{
      e = FalseLiteral();
      break;
      }
    case IDENTIFIER:{
      i = Identifier();
e = new IdentifierExp(i.line, i.column, i.s);
      break;
      }
    case THIS:{
      e = ThisExpression();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      if (jj_2_4(3)) {
        e = ArrayAllocationExpression();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:{
          e = AllocationExpression();
          break;
          }
        case LPAREN:{
          jj_consume_token(LPAREN);
          e = Expression();
          jj_consume_token(RPAREN);
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  final public Exp IntegerLiteral() throws ParseException {Token t = null;
    t = jj_consume_token(INTEGER_LITERAL);
{if ("" != null) return new IntegerLiteral(t.beginLine, t.beginColumn, Integer.parseInt(t.image));}
    throw new Error("Missing return statement in function");
}

  final public Exp TrueLiteral() throws ParseException {Token t = null;
    t = jj_consume_token(TRUE);
{if ("" != null) return new True(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
}

  final public Exp FalseLiteral() throws ParseException {Token t = null;
    t = jj_consume_token(FALSE);
{if ("" != null) return new False(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
}

  final public Exp ThisExpression() throws ParseException {Token t = null;
    t = jj_consume_token(THIS);
{if ("" != null) return new This(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
}

  final public Exp ArrayAllocationExpression() throws ParseException {Exp size; Token t = null;
    t = jj_consume_token(NEW);
    jj_consume_token(INT);
    jj_consume_token(LBRACK);
    size = Expression();
    jj_consume_token(RBRACK);
{if ("" != null) return new NewArray(t.beginLine, t.beginColumn, size);}
    throw new Error("Missing return statement in function");
}

  final public Exp AllocationExpression() throws ParseException {Identifier i; Token t = null;
    t = jj_consume_token(NEW);
    i = Identifier();
    jj_consume_token(LPAREN);
    jj_consume_token(RPAREN);
{if ("" != null) return new NewObject(t.beginLine, t.beginColumn, i);}
    throw new Error("Missing return statement in function");
}

  final public Exp PostfixExpression() throws ParseException {Exp e1, e2; Identifier i; ExpList el; Token t = null;
    e1 = PrimaryExpression();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACK:
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACK:{
        t = jj_consume_token(LBRACK);
        e2 = Expression();
        jj_consume_token(RBRACK);
e1 = new ArrayLookup(t.beginLine, t.beginColumn, e1, e2);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        if (jj_2_5(2)) {
          t = jj_consume_token(DOT);
          jj_consume_token(LENGTH);
e1 = new ArrayLength(t.beginLine, t.beginColumn, e1);
        } else if (jj_2_6(2147483647)) {
          t = jj_consume_token(DOT);
          i = Identifier();
          jj_consume_token(LPAREN);
el = new ExpList();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TRUE:
          case FALSE:
          case THIS:
          case NEW:
          case LPAREN:
          case BANG:
          case IDENTIFIER:
          case INTEGER_LITERAL:{
            el = ExpressionList();
            break;
            }
          default:
            jj_la1[13] = jj_gen;
            ;
          }
          jj_consume_token(RPAREN);
e1 = new Call(t.beginLine, t.beginColumn, e1, i, el);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  final public Exp Expression() throws ParseException {Exp e; Token t = null;
    e = AndExpression();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  final public ExpList ExpressionList() throws ParseException {ExpList el = new ExpList(); Exp e;
    e = Expression();
el.addElement(e);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_10;
      }
      e = ExpressionRest();
el.addElement(e);
    }
{if ("" != null) return el;}
    throw new Error("Missing return statement in function");
}

  final public Exp ExpressionRest() throws ParseException {Exp e; Token t = null;
    jj_consume_token(COMMA);
    e = Expression();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  final public Exp UnaryExpression() throws ParseException {Exp e; Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BANG:{
      t = jj_consume_token(BANG);
      e = UnaryExpression();
{if ("" != null) return new Not(t.beginLine, t.beginColumn, e);}
      break;
      }
    case TRUE:
    case FALSE:
    case THIS:
    case NEW:
    case LPAREN:
    case IDENTIFIER:
    case INTEGER_LITERAL:{
      e = PostfixExpression();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Exp MulExpression() throws ParseException {Exp e1, e2; Token t = null;
    e1 = UnaryExpression();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STAR:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_11;
      }
      t = jj_consume_token(STAR);
      e2 = UnaryExpression();
e1 = new Times(t.beginLine, t.beginColumn, e1, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  final public Exp AddExpression() throws ParseException {Exp e1, e2; Token op;
    e1 = MulExpression();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        op = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        op = jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      e2 = MulExpression();
if (op.kind == PLUS) e1 = new Plus(op.beginLine, op.beginColumn, e1, e2); else e1 = new Minus(op.beginLine, op.beginColumn, e1, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  final public Exp CompareExpression() throws ParseException {Exp e1, e2; Token t = null;
    e1 = AddExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_13;
      }
      t = jj_consume_token(LT);
      e2 = AddExpression();
e1 = new LessThan(t.beginLine, t.beginColumn, e1, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  final public Exp AndExpression() throws ParseException {Exp e1, e2; Token t = null;
    e1 = CompareExpression();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_14;
      }
      t = jj_consume_token(AND);
      e2 = CompareExpression();
e1 = new And(t.beginLine, t.beginColumn, e1, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  final public Statement Block() throws ParseException {StatementList sl = new StatementList(); Statement s; Token t = null;
    t = jj_consume_token(LBRACE);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case PRINTLN:
      case LBRACE:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_15;
      }
      s = Statement();
sl.addElement(s);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new Block(t.beginLine, t.beginColumn, sl);}
    throw new Error("Missing return statement in function");
}

  final public Statement Statement() throws ParseException {Statement s;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACE:{
      s = Block();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      if (jj_2_7(2)) {
        s = AssignmentStatement();
      } else if (jj_2_8(2)) {
        s = ArrayAssignmentStatement();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IF:{
          s = IfStatement();
          break;
          }
        case WHILE:{
          s = WhileStatement();
          break;
          }
        case PRINTLN:{
          s = PrintStatement();
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
{if ("" != null) return s;}
    throw new Error("Missing return statement in function");
}

  final public Statement PrintStatement() throws ParseException {Exp e; Token t = null;
    t = jj_consume_token(PRINTLN);
    jj_consume_token(LPAREN);
    e = Expression();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMI);
{if ("" != null) return new Print(t.beginLine, t.beginColumn, e);}
    throw new Error("Missing return statement in function");
}

  final public Statement WhileStatement() throws ParseException {Exp e; Statement s; Token t = null;
    t = jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    e = Expression();
    jj_consume_token(RPAREN);
    s = Statement();
{if ("" != null) return new While(t.beginLine, t.beginColumn, e, s);}
    throw new Error("Missing return statement in function");
}

  final public Statement IfStatement() throws ParseException {Exp e; Statement s1, s2; Token t = null;
    t = jj_consume_token(IF);
    jj_consume_token(LPAREN);
    e = Expression();
    jj_consume_token(RPAREN);
    s1 = Statement();
    jj_consume_token(ELSE);
    s2 = Statement();
{if ("" != null) return new If(t.beginLine, t.beginColumn, e, s1, s2);}
    throw new Error("Missing return statement in function");
}

  final public Statement ArrayAssignmentStatement() throws ParseException {Identifier i; Exp e1, e2;
    i = Identifier();
    jj_consume_token(LBRACK);
    e1 = Expression();
    jj_consume_token(RBRACK);
    jj_consume_token(ASSIGN);
    e2 = Expression();
    jj_consume_token(SEMI);
{if ("" != null) return new ArrayAssign(i.line, i.column, i, e1, e2);}
    throw new Error("Missing return statement in function");
}

  final public Statement AssignmentStatement() throws ParseException {Identifier i; Exp e;
    i = Identifier();
    jj_consume_token(ASSIGN);
    e = Expression();
    jj_consume_token(SEMI);
{if ("" != null) return new Assign(i.line, i.column, i, e);}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_3_2()
 {
    if (jj_3R_VarDeclaration_121_5_17()) return true;
    return false;
  }

  private boolean jj_3R_IntegerType_179_5_28()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_AssignmentStatement_367_5_21()
 {
    if (jj_3R_Identifier_185_5_20()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_Identifier_185_5_20()) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_BooleanType_173_5_27()
 {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  private boolean jj_3R_ArrayAssignmentStatement_360_5_22()
 {
    if (jj_3R_Identifier_185_5_20()) return true;
    if (jj_scan_token(LBRACK)) return true;
    return false;
  }

  private boolean jj_3R_VarDeclaration_121_5_17()
 {
    if (jj_3R_Type_158_7_23()) return true;
    if (jj_3R_Identifier_185_5_20()) return true;
    return false;
  }

  private boolean jj_3R_ArrayType_167_5_18()
 {
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(LBRACK)) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  private boolean jj_3R_Type_161_7_26()
 {
    if (jj_3R_Identifier_185_5_20()) return true;
    return false;
  }

  private boolean jj_3R_Type_160_7_25()
 {
    if (jj_3R_IntegerType_179_5_28()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  private boolean jj_3R_Type_159_7_24()
 {
    if (jj_3R_BooleanType_173_5_27()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_ArrayType_167_5_18()) return true;
    return false;
  }

  private boolean jj_3R_Type_158_7_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_159_7_24()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_160_7_25()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_161_7_26()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_ArrayAllocationExpression_234_5_19()) return true;
    return false;
  }

  private boolean jj_3R_ClassDeclaration_101_5_16()
 {
    if (jj_scan_token(CLASS)) return true;
    if (jj_3R_Identifier_185_5_20()) return true;
    if (jj_scan_token(LBRACE)) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_ArrayAssignmentStatement_360_5_22()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_ClassDeclaration_101_5_16()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_AssignmentStatement_367_5_21()) return true;
    return false;
  }

  private boolean jj_3R_ArrayAllocationExpression_234_5_19()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(LBRACK)) return true;
    return false;
  }

  private boolean jj_3R_Identifier_185_5_20()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MiniJavaParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[25];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x80,0x80,0x18000,0x100,0x18000,0x100,0x18000,0x41a0000,0x0,0x18000,0x1c00000,0x12000000,0x40000000,0x13c00000,0x40000000,0x0,0x13c00000,0x0,0x0,0x0,0x0,0x0,0x41a0000,0x4000000,0x1a0000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x400,0x0,0x400,0x0,0x400,0x400,0x2,0x400,0xc00,0x0,0x100,0xe00,0x0,0x2,0xe00,0x80,0x60,0x60,0x10,0x8,0x400,0x0,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[8];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 jj_input_stream = new JavaCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new JavaCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[44];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 25; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 44; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 8; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
